variables:
  - &rust_image "rust:1.79-slim-bookworm"

steps:
  toml_fmt:
    image: tamasfe/taplo:0.8.1
    commands:
      - taplo format --check
    when:
      - event: pull_request
    depends_on: [] # enable parallel steps

  cargo_fmt:
    image: rustlang/rust:nightly-alpine
    commands:
      - rustup component add rustfmt
      - cargo +nightly fmt -- --check
    when:
      - event: pull_request

  cargo_machete:
    image: *rust_image
    commands:
      - apt update && apt -y install wget
      - wget -O- https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -xvz -C /usr/local/cargo/bin
      - cargo binstall -y cargo-machete
      - cargo machete
    when:
      - event: pull_request

  cargo_clippy:
    image: *rust_image
    commands:
      - apt update && apt install pkg-config libssl-dev -y
      - rustup component add clippy
      - cargo clippy --tests --all-targets -- -D warnings
    when:
      - event: pull_request

  cargo_build:
    image: *rust_image
    commands:
      - apt update && apt install pkg-config libssl-dev -y
      - cargo build
    when:
      - event: pull_request

  cargo_test:
    image: *rust_image
    environment:
      RUST_BACKTRACE: "1"
    commands:
      - apt update && apt install pkg-config libssl-dev -y
      - cargo test --no-fail-fast
    when:
      - event: pull_request

  publish_to_crates_io:
    image: *rust_image
    commands:
      - cargo publish --allow-dirty --no-verify --token "$CARGO_API_TOKEN"
    secrets: [cargo_api_token]
    when:
      - event: tag

  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'lemmy-client-rs CI build failed: ${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: [pull_request, tag]
        status: failure

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'lemmy-client-rs:${CI_COMMIT_TAG} deployed' ntfy.sh/lemmy_drone_ci"
    when:
      - event: tag
