variables:
  - &rust_image "rust:1.90-slim-bookworm"

steps:
  toml_fmt:
    image: tamasfe/taplo:0.9.3
    commands:
      - taplo format --check
    when:
      - event: pull_request

  cargo_fmt:
    image: rustlang/rust:nightly-alpine
    commands:
      - rustup component add rustfmt
      - cargo +nightly fmt -- --check
    when:
      - event: pull_request

  cargo_machete:
    image: *rust_image
    commands:
      - apt update && apt -y install wget
      - wget -O- https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -xvz -C /usr/local/cargo/bin
      - cargo binstall -y cargo-machete
      - cargo machete
    when:
      - event: pull_request

  cargo_clippy:
    image: *rust_image
    commands:
      - apt update && apt install pkg-config libssl-dev -y
      - rustup component add clippy
      - cargo clippy --tests --all-targets -- -D warnings
    when:
      - event: pull_request

  cargo_build:
    image: *rust_image
    commands:
      - apt update && apt install pkg-config libssl-dev -y
      - cargo build
    when:
      - event: pull_request

  cargo_test:
    image: *rust_image
    environment:
      RUST_BACKTRACE: "1"
    commands:
      - apt update && apt install pkg-config libssl-dev -y
      - cargo test --no-fail-fast
    when:
      - event: pull_request

  publish_to_crates_io:
    image: *rust_image
    environment:
      CARGO_API_TOKEN:
        from_secret: cargo_api_token
    commands:
      - cargo publish --allow-dirty --no-verify --token "$CARGO_API_TOKEN"
    when:
      - event: tag

  notify_success:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ✔️ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [success]

  notify_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ❌ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ${CI_REPO_NAME}:${CI_COMMIT_TAG} deployed' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag
