[package]
name = "lemmy-client"
version = "1.0.0-test-fix-publish-3"
edition = "2024"
license = "AGPL-3.0"
authors = ["SleeplessOne1917"]
description = "A Rust HTTP client for Lemmy."
homepage = "https://join-lemmy.org"
repository = "https://github.com/LemmyNet/lemmy-client-rs"
keywords = ["Lemmy", "HTTP-client", "API-wrapper", "fediverse"]
categories = ["api-bindings", "wasm"]

[dependencies]
lemmy_api_common = "1.0.0-test-fix-publish-3"
http = "1.4"
reqwest = { version = "0.13", features = [
  "json",
  "query",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
