use crate::{
    form::{LemmyForm, LemmyRequest},
    response::{LemmyResponse, LemmyResult},
};
use http::Method;
use lemmy_api_common::{
    comment::*,
    community::*,
    custom_emoji::*,
    person::*,
    post::*,
    private_message::*,
    reports::{comment::*, post::*, private_message::*},
    site::*,
    tagline::{
        CreateTagline, DeleteTagline, ListTaglines, ListTaglinesResponse, TaglineResponse,
        UpdateTagline,
    },
    SuccessResponse,
};
use std::collections::HashMap;

pub mod private_trait {
    use super::{HashMap, LemmyForm, LemmyRequest, LemmyResponse, LemmyResult, Method};

    pub trait LemmyClientInternal {
        async fn make_request<Response, Form>(
            &self,
            method: Method,
            path: &str,
            request: LemmyRequest<Form>,
            headers: &HashMap<String, String>,
        ) -> LemmyResult<Response>
        where
            Response: LemmyResponse,
            Form: LemmyForm;
    }
}

macro_rules! client_fn {
    ($name:ident, $method:expr, $path:expr, $form:ty, $response:ty) => {
        async fn $name(
            &self,
            request: LemmyRequest<$form>,
            headers: &HashMap<String, String>,
        ) -> LemmyResult<$response> {
            self.make_request($method, $path, request, headers).await
        }
    };
}

pub trait LemmyClientInternal: private_trait::LemmyClientInternal {
    client_fn!(get_site, Method::GET, "site", (), GetSiteResponse);
    client_fn!(create_site, Method::POST, "site", CreateSite, SiteResponse);
    client_fn!(edit_site, Method::PUT, "site", EditSite, SiteResponse);
    // TODO: Add stuff for icon and banner
    client_fn!(
        get_modlog,
        Method::GET,
        "modlog",
        GetModlog,
        GetModlogResponse
    );
    client_fn!(search, Method::GET, "search", Search, SearchResponse);
    client_fn!(
        resolve_object,
        Method::GET,
        "resolve_object",
        ResolveObject,
        ResolveObjectResponse
    );
    client_fn!(
        get_community,
        Method::GET,
        "community",
        GetCommunity,
        GetCommunityResponse
    );
    client_fn!(
        create_community,
        Method::POST,
        "community",
        CreateCommunity,
        CommunityResponse
    );
    client_fn!(
        update_community,
        Method::PUT,
        "community",
        EditCommunity,
        CommunityResponse
    );
    client_fn!(
        get_random_community,
        Method::GET,
        "community/random",
        GetRandomCommunity,
        CommunityResponse
    );
    client_fn!(
        hide_community,
        Method::PUT,
        "community/hide",
        HideCommunity,
        SuccessResponse
    );
    client_fn!(
        list_communities,
        Method::GET,
        "community/list",
        ListCommunities,
        ListCommunitiesResponse
    );
    client_fn!(
        follow_community,
        Method::POST,
        "community/follow",
        FollowCommunity,
        CommunityResponse
    );
    client_fn!(
        delete_community,
        Method::POST,
        "community/delete",
        DeleteCommunity,
        CommunityResponse
    );
    client_fn!(
        remove_community,
        Method::POST,
        "community/remove",
        RemoveCommunity,
        CommunityResponse
    );
    client_fn!(
        transfer_community,
        Method::POST,
        "community/transfer",
        TransferCommunity,
        GetCommunityResponse
    );
    client_fn!(
        ban_from_community,
        Method::POST,
        "community/ban_user",
        BanFromCommunity,
        BanFromCommunityResponse
    );
    client_fn!(
        add_mod_to_community,
        Method::POST,
        "community/mod",
        AddModToCommunity,
        AddModToCommunityResponse
    );
    // TODO: Add icon and banner stuff
    client_fn!(
        get_community_pending_follows_count,
        Method::GET,
        "community/pending_follows/count",
        GetCommunityPendingFollowsCount,
        GetCommunityPendingFollowsCountResponse
    );
    client_fn!(
        list_community_pending_follows,
        Method::GET,
        "community/pending_follows/list",
        ListCommunityPendingFollows,
        ListCommunityPendingFollowsResponse
    );
    client_fn!(
        approve_community_pending_follow,
        Method::POST,
        "community/pending_follows/approve",
        ApproveCommunityPendingFollower,
        SuccessResponse
    );
    client_fn!(
        get_federated_instances,
        Method::GET,
        "federated_instances",
        FederatedInstances,
        GetFederatedInstancesResponse
    );
    client_fn!(get_post, Method::GET, "post", GetPost, GetPostResponse);
    client_fn!(create_post, Method::POST, "post", CreatePost, PostResponse);
    client_fn!(edit_post, Method::PUT, "post", EditPost, PostResponse);
    client_fn!(
        get_post_url_metadata,
        Method::GET,
        "post/site_metadata",
        GetSiteMetadata,
        GetSiteMetadataResponse
    );
    client_fn!(
        delete_post,
        Method::POST,
        "post/delete",
        DeletePost,
        PostResponse
    );
    client_fn!(
        remove_post,
        Method::POST,
        "post/remove",
        RemovePost,
        PostResponse
    );
    client_fn!(
        mark_post_as_read,
        Method::POST,
        "post/mark_as_read",
        MarkPostAsRead,
        SuccessResponse
    );
    client_fn!(
        mark_many_posts_as_read,
        Method::POST,
        "post/mark_as_read/many",
        MarkManyPostsAsRead,
        SuccessResponse
    );
    client_fn!(
        hide_post,
        Method::POST,
        "post/hide",
        HidePost,
        SuccessResponse
    );
    client_fn!(lock_post, Method::POST, "post/lock", LockPost, PostResponse);
    client_fn!(
        feature_post,
        Method::POST,
        "post/feature",
        FeaturePost,
        PostResponse
    );
    client_fn!(
        list_posts,
        Method::GET,
        "post/list",
        GetPosts,
        GetPostsResponse
    );
    client_fn!(
        like_post,
        Method::POST,
        "post/like",
        CreatePostLike,
        PostResponse
    );
    client_fn!(
        list_post_likes,
        Method::GET,
        "post/like/list",
        ListPostLikes,
        ListPostLikesResponse
    );
    client_fn!(save_post, Method::PUT, "post/save", SavePost, PostResponse);
    client_fn!(
        report_post,
        Method::POST,
        "post/report",
        CreatePostReport,
        PostReportResponse
    );
    client_fn!(
        resolve_post_report,
        Method::PUT,
        "post/report/resolve",
        ResolvePostReport,
        PostReportResponse
    );
    client_fn!(
        get_comment,
        Method::GET,
        "comment",
        GetComment,
        CommentResponse
    );
    client_fn!(
        create_comment,
        Method::POST,
        "comment",
        CreateComment,
        CommentResponse
    );
    client_fn!(
        edit_comment,
        Method::PUT,
        "comment",
        EditComment,
        CommentResponse
    );
    client_fn!(
        delete_comment,
        Method::POST,
        "comment/delete",
        DeleteComment,
        CommentResponse
    );
    client_fn!(
        remove_comment,
        Method::POST,
        "comment/remove",
        RemoveComment,
        CommentResponse
    );
    client_fn!(
        mark_reply_as_read,
        Method::POST,
        "comment/mark_as_read",
        MarkCommentReplyAsRead,
        SuccessResponse
    );
    client_fn!(
        distinguish_comment,
        Method::POST,
        "comment/distinguish",
        DistinguishComment,
        CommentResponse
    );
    client_fn!(
        like_comment,
        Method::POST,
        "comment/like",
        CreateCommentLike,
        CommentResponse
    );
    client_fn!(
        list_comment_likes,
        Method::GET,
        "comment/like/list",
        ListCommentLikes,
        ListCommentLikesResponse
    );
    client_fn!(
        save_comment,
        Method::PUT,
        "comment/save",
        SaveComment,
        CommentResponse
    );
    client_fn!(
        list_comments,
        Method::GET,
        "comment/list",
        GetComments,
        GetCommentsResponse
    );
    client_fn!(
        list_comments_slim,
        Method::GET,
        "comment/list/slim",
        GetComments,
        GetCommentsSlimResponse
    );
    client_fn!(
        create_comment_report,
        Method::POST,
        "comment/report",
        CreateCommentReport,
        CommentResponse
    );
    client_fn!(
        resolve_comment_report,
        Method::PUT,
        "comment/report/resolve",
        ResolveCommentReport,
        CommentReportResponse
    );
    client_fn!(
        create_private_message,
        Method::POST,
        "private_message",
        CreatePrivateMessage,
        PrivateMessageResponse
    );
    client_fn!(
        edit_private_message,
        Method::PUT,
        "private_message",
        EditPrivateMessage,
        PrivateMessageResponse
    );
    client_fn!(
        delete_private_message,
        Method::POST,
        "private_message/delete",
        DeletePrivateMessage,
        PrivateMessageResponse
    );
    client_fn!(
        mark_private_message_as_read,
        Method::POST,
        "private_message/mark_as_read",
        MarkPrivateMessageAsRead,
        PrivateMessageResponse
    );
    client_fn!(
        create_private_message_report,
        Method::POST,
        "private_message/report",
        CreatePrivateMessageReport,
        PrivateMessageReportResponse
    );
    client_fn!(
        resolve_private_message_report,
        Method::PUT,
        "private_message/report/resolve",
        ResolvePrivateMessageReport,
        PrivateMessageReportResponse
    );
    client_fn!(
        register_account,
        Method::POST,
        "account/auth/register",
        Register,
        LoginResponse
    );
    client_fn!(
        login,
        Method::POST,
        "account/auth/login",
        Login,
        LoginResponse
    );
    client_fn!(
        logout,
        Method::POST,
        "account/auth/logout",
        (),
        SuccessResponse
    );
    client_fn!(
        reset_password,
        Method::POST,
        "account/auth/password_reset",
        PasswordReset,
        SuccessResponse
    );
    client_fn!(
        get_captcha,
        Method::GET,
        "account/auth/get_captcha",
        (),
        GetCaptchaResponse
    );
    client_fn!(
        change_password_after_reset,
        Method::POST,
        "account/auth/password_change",
        PasswordChangeAfterReset,
        SuccessResponse
    );
    client_fn!(
        change_password,
        Method::PUT,
        "account/auth/change_password",
        ChangePassword,
        LoginResponse
    );
    client_fn!(
        generate_totp_secret,
        Method::POST,
        "account/auth/totp/generate",
        (),
        GenerateTotpSecretResponse
    );
    client_fn!(
        update_totp,
        Method::POST,
        "account/auth/totp/update",
        UpdateTotp,
        UpdateTotpResponse
    );
    client_fn!(
        verify_email,
        Method::POST,
        "account/auth/verify_email",
        VerifyEmail,
        SuccessResponse
    );
    client_fn!(
        list_saved,
        Method::GET,
        "account/auth/saved",
        ListPersonSaved,
        ListPersonSavedResponse
    );
    client_fn!(get_current_user, Method::GET, "account", (), MyUserInfo);
    client_fn!(
        list_media,
        Method::GET,
        "account/list_media",
        ListMedia,
        ListMediaResponse
    );
    client_fn!(
        list_inbox,
        Method::GET,
        "account/inbox",
        ListInbox,
        ListInboxResponse
    );
    client_fn!(
        delete_account,
        Method::POST,
        "account/delete",
        DeleteAccount,
        SuccessResponse
    );
    client_fn!(
        mark_comment_mention_as_read,
        Method::POST,
        "account/mention/comment/mark_as_read",
        MarkPersonCommentMentionAsRead,
        SuccessResponse
    );
    client_fn!(
        mark_post_mention_as_read,
        Method::POST,
        "account/mention/post/mark_as_read",
        MarkPersonPostMentionAsRead,
        SuccessResponse
    );
    client_fn!(
        mark_all_notifications_as_read,
        Method::POST,
        "account/mark_as_read/all",
        (),
        SuccessResponse
    );
    client_fn!(
        report_count,
        Method::GET,
        "account/report_count",
        GetReportCount,
        GetReportCountResponse
    );
    client_fn!(
        unread_count,
        Method::GET,
        "account/unread_count",
        (),
        GetUnreadCountResponse
    );
    client_fn!(
        list_logins,
        Method::GET,
        "account/list_logins",
        (),
        ListLoginsResponse
    );
    client_fn!(
        validate_auth,
        Method::GET,
        "account/validate_auth",
        (),
        SuccessResponse
    );
    client_fn!(
        donation_dialog_shown,
        Method::POST,
        "account/donation_dialog_shown",
        (),
        SuccessResponse
    );
    // TODO: Handle Account avatar and banner
    client_fn!(
        block_person,
        Method::POST,
        "account/block/person",
        BlockPerson,
        BlockPersonResponse
    );
    client_fn!(
        block_community,
        Method::POST,
        "account/block/community",
        BlockCommunity,
        BlockCommunityResponse
    );
    client_fn!(
        user_block_instance,
        Method::POST,
        "account/block/instance",
        UserBlockInstanceParams,
        SuccessResponse
    );
    client_fn!(
        save_user_settings,
        Method::PUT,
        "account/settings/save",
        SaveUserSettings,
        SuccessResponse
    );
    client_fn!(
        export_settings,
        Method::GET,
        "account/settings/export",
        (),
        String
    );
    // TODO: How to handle import?
    client_fn!(
        import_settings,
        Method::POST,
        "account/settings/import",
        String,
        SuccessResponse
    );
    client_fn!(
        get_person_details,
        Method::GET,
        "person",
        GetPersonDetails,
        GetPersonDetailsResponse
    );
    client_fn!(
        list_person_content,
        Method::GET,
        "person/content",
        ListPersonContent,
        ListPersonContentResponse
    );
    client_fn!(
        add_admin,
        Method::POST,
        "admin/add",
        AddAdmin,
        AddAdminResponse
    );
    client_fn!(
        unread_registration_application_count,
        Method::GET,
        "admin/registration_application/count",
        (),
        GetUnreadRegistrationApplicationCountResponse
    );
    client_fn!(
        list_registration_applications,
        Method::GET,
        "admin/registration_application/list",
        ListRegistrationApplications,
        ListRegistrationApplicationsResponse
    );
    client_fn!(
        approve_registration_application,
        Method::PUT,
        "admin/registration_application/approve",
        ApproveRegistrationApplication,
        RegistrationApplicationResponse
    );
    client_fn!(
        get_registration_aplication,
        Method::GET,
        "admin/registration_application",
        GetRegistrationApplication,
        RegistrationApplicationResponse
    );
    client_fn!(
        list_all_media,
        Method::GET,
        "admin/list_all_media",
        ListMedia,
        ListMediaResponse
    );
    client_fn!(
        purge_person,
        Method::POST,
        "admin/purge/person",
        PurgePerson,
        SuccessResponse
    );
    client_fn!(
        purge_community,
        Method::POST,
        "admin/purge/community",
        PurgeCommunity,
        SuccessResponse
    );
    client_fn!(
        purge_post,
        Method::POST,
        "admin/purge/post",
        PurgePost,
        SuccessResponse
    );
    client_fn!(
        purge_comment,
        Method::POST,
        "admin/purge/comment",
        PurgeComment,
        SuccessResponse
    );
    client_fn!(
        create_tagline,
        Method::POST,
        "admin/tagline",
        CreateTagline,
        TaglineResponse
    );
    client_fn!(
        update_tagline,
        Method::PUT,
        "admin/tagline",
        UpdateTagline,
        TaglineResponse
    );
    client_fn!(
        delete_tagline,
        Method::POST,
        "admin/tagline/delete",
        DeleteTagline,
        SuccessResponse
    );
    client_fn!(
        list_taglines,
        Method::GET,
        "admin/tagline/list",
        ListTaglines,
        ListTaglinesResponse
    );
    client_fn!(
        ban_from_site,
        Method::POST,
        "admin/ban",
        BanPerson,
        BanPersonResponse
    );
    client_fn!(
        list_banned_users,
        Method::GET,
        "admin/banned",
        (),
        BannedPersonsResponse
    );
    client_fn!(
        leave_admin,
        Method::POST,
        "admin/leave",
        (),
        GetSiteResponse
    );
    client_fn!(
        admin_block_instance,
        Method::POST,
        "admin/instance/block",
        AdminBlockInstanceParams,
        SuccessResponse
    );
    client_fn!(
        admin_allow_instance,
        Method::POST,
        "admin/instance/allow",
        AdminAllowInstanceParams,
        SuccessResponse
    );
    client_fn!(
        create_custom_emoji,
        Method::POST,
        "admin/custom_emoji",
        CreateCustomEmoji,
        CustomEmojiResponse
    );
    client_fn!(
        edit_custom_emoji,
        Method::PUT,
        "admin/custom_emoji",
        EditCustomEmoji,
        CustomEmojiResponse
    );
    client_fn!(
        delete_custom_emoji,
        Method::POST,
        "admin/custom_emoji/delete",
        DeleteCustomEmoji,
        CustomEmojiResponse
    );
    client_fn!(
        list_custom_emojis,
        Method::GET,
        "admin/custom_emoji/list",
        ListCustomEmojis,
        ListCustomEmojisResponse
    );
}
